# Generated by Django 4.1.5 on 2023-01-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('phone_number', models.PositiveBigIntegerField(unique=True)),
                ('mail_id', models.EmailField(max_length=200, unique=True)),
                ('address', models.TextField(max_length=100)),
                ('district', models.CharField(choices=[('CH', 'chennai'), ('Ma', 'madurai'), ('TR', 'trichy'), ('SA', 'salem')], default='chennai', max_length=200)),
                ('branch', models.CharField(choices=[('Ad', 'adayar'), ('Na', 'navalur'), ('Si', 'siruseri')], default='adayar', max_length=200)),
                ('account_type', models.CharField(choices=[('CA', 'current'), ('SA', 'savings')], default='savings', max_length=200)),
                ('credit_card', models.BooleanField()),
                ('debit_card', models.BooleanField()),
                ('cheque_book', models.BooleanField()),
            ],
        ),
    ]
